// Products Context
export const GET_POPULAR_PRODUCTS = 'GET_POPULAR_PRODUCTS';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_DESIGNER_PRODUCTS = 'GET_DESIGNER_PRODUCTS';
export const GET_DESIGNER = 'GET_DESIGNER';

// Filters Context
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const UPDATE_SORT = 'UPDATE_SORT';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

// Cart Context
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const SELECT_SIZE = 'SELECT_SIZE';
export const SHOW_CART_MODEL = 'SHOW_CART_MODEL';
export const HIDE_CART_MODEL = 'HIDE_CART_MODEL';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const GET_CART_SUBTOTAL = 'GET_CART_SUBTOTAL';
