export const GET_POPULAR_PRODUCTS = 'GET_POPULAR_PRODUCTS';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_DESIGNER_PRODUCTS = 'GET_DESIGNER_PRODUCTS';
