import { v4 as uuidv4 } from 'uuid';

export default function addDataBase(firebase) {
  const dataBase = firebase.firestore();
  //   dataBase.settings({ timestampsInSnapshots: true });

  /* men
    ============================================ */
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'isaac sellam epicurien-wax pants',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     images: [
  //       'isaac_sellam_epicurien_wax_pants_stone_white_1',
  //       'isaac_sellam_epicurien_wax_pants_stone_white_2',
  //       'isaac_sellam_epicurien_wax_pants_stone_white_3',
  //       'isaac_sellam_epicurien_wax_pants_stone_white_4',
  //     ],
  //     price: 67000,
  //     discountPer: 70,
  //     color: 'stone',
  //     sku: 'epicurien-wax~stone',
  //     collection: 'SS20 New Collection',
  //     desc: 'Waxed Slim Pants by ISAAC SELLAM in Stone White',
  //     details: [
  //       'Natural waist rise',
  //       'Slim fit',
  //       'Concealed buttons closure',
  //       'Belt hooks',
  //       'Two side slant pockets with signature staple details',
  //       'Back welt pockets',
  //       'Scar seams throughout',
  //       'Dye effect may vary',
  //     ],
  //     sizes: [
  //       { size: 's', isAvailable: false },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: false },
  //       { size: 'xl', isAvailable: true },
  //       { size: 'xxl', isAvailable: false },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: true,
  //     stock: 25,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'isaac sellam epicurien-wax pants',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     images: [
  //       'isaac_sellam_epicurien_wax_pants_dark_grey_1',
  //       'isaac_sellam_epicurien_wax_pants_dark_grey_2',
  //       'isaac_sellam_epicurien_wax_pants_dark_grey_3',
  //       'isaac_sellam_epicurien_wax_pants_dark_grey_4',
  //     ],
  //     price: 67000,
  //     discountPer: 70,
  //     color: 'dark grey',
  //     sku: 'epicurien-wax~dark grey',
  //     collection: 'SS20 New Collection',
  //     desc: 'Waxed Slim Pants by ISAAC SELLAM in Dark Grey',
  //     details: [
  //       'Natural waist rise',
  //       'Slim fit',
  //       'Concealed buttons closure',
  //       'Belt hooks',
  //       'Two side slant pockets with signature staple details',
  //       'Back welt pockets',
  //       'Scar seams throughout',
  //       'Dye effect may vary',
  //     ],
  //     sizes: [
  //       { size: 's', isAvailable: false },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: false },
  //       { size: 'xl', isAvailable: true },
  //       { size: 'xxl', isAvailable: false },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: true,
  //     stock: 10,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'isaac sellam epicurien-wax pants',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     images: [
  //       'isaac_sellam_epicurien_wax_pants_bronze_1',
  //       'isaac_sellam_epicurien_wax_pants_bronze_2',
  //       'isaac_sellam_epicurien_wax_pants_bronze_3',
  //       'isaac_sellam_epicurien_wax_pants_bronze_4',
  //     ],
  //     price: 67000,
  //     discountPer: 70,
  //     color: 'bronze',
  //     sku: 'epicurien-wax~bronze',
  //     collection: 'SS20 New Collection',
  //     desc: 'Waxed Slim Pants by ISAAC SELLAM in Bronze',
  //     details: [
  //       'Natural waist rise',
  //       'Slim fit',
  //       'Concealed buttons closure',
  //       'Belt hooks',
  //       'Two side slant pockets with signature staple details',
  //       'Back welt pockets',
  //       'Scar seams throughout',
  //       'Dye effect may vary',
  //     ],
  //     sizes: [
  //       { size: 's', isAvailable: true },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: true },
  //       { size: 'xl', isAvailable: true },
  //       { size: 'xxl', isAvailable: true },
  //       { size: 'xxxl', isAvailable: true },
  //     ],
  //     popularity: false,
  //     stock: 9,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'isaac sellam epicurien-wax pants',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     images: [
  //       'isaac_sellam_epicurien_wax_pants_white_1',
  //       'isaac_sellam_epicurien_wax_pants_white_2',
  //       'isaac_sellam_epicurien_wax_pants_white_3',
  //       'isaac_sellam_epicurien_wax_pants_white_4',
  //     ],
  //     price: 67000,
  //     discountPer: 70,
  //     color: 'white',
  //     sku: 'epicurien-wax~white',
  //     collection: 'SS20 New Collection',
  //     desc: 'Waxed Slim Pants by ISAAC SELLAM in White',
  //     details: [
  //       'Natural waist rise',
  //       'Slim fit',
  //       'Concealed buttons closure',
  //       'Belt hooks',
  //       'Two side slant pockets with signature staple details',
  //       'Back welt pockets',
  //       'Scar seams throughout',
  //     ],
  //     sizes: [
  //       { size: 's', isAvailable: false },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: false },
  //       { size: 'xl', isAvailable: false },
  //       { size: 'xxl', isAvailable: false },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: false,
  //     stock: 14,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'isaac sellam epicurien-wax pants',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     images: [
  //       'isaac_sellam_epicurien_wax_pants_petrole_1',
  //       'isaac_sellam_epicurien_wax_pants_petrole_2',
  //       'isaac_sellam_epicurien_wax_pants_petrole_3',
  //       'isaac_sellam_epicurien_wax_pants_petrole_4',
  //     ],
  //     price: 67000,
  //     discountPer: 70,
  //     color: 'petrole',
  //     sku: 'epicurien-wax~petrole',
  //     collection: 'SS20 New Collection',
  //     desc: 'Waxed Slim Pants by ISAAC SELLAM in Petrole',
  //     details: [
  //       'Natural waist rise',
  //       'Slim fit',
  //       'Concealed buttons closure',
  //       'Belt hooks',
  //       'Two side slant pockets with signature staple details',
  //       'Back welt pockets',
  //       'Scar seams throughout',
  //       'Dye effect may vary',
  //     ],
  //     sizes: [
  //       { size: 's', isAvailable: false },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: false },
  //       { size: 'xl', isAvailable: false },
  //       { size: 'xxl', isAvailable: false },
  //       { size: 'xxxl', isAvailable: true },
  //     ],
  //     popularity: false,
  //     stock: 8,
  //   });

  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'epicurien-wax',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     images: [
  //       'epicurien_wax_black_1',
  //       'epicurien_wax_black_2',
  //       'epicurien_wax_black_3',
  //       'epicurien_wax_black_4',
  //     ],
  //     color: 'black',
  //     sku: 'epicurien-wax~black',
  //     desc: 'Waxed Slim Pants by ISAAC SELLAM in black',
  //     details: [
  //       'Natural waist rise',
  //       'Slim fit',
  //       'Concealed buttons closure',
  //       'Belt hooks',
  //       'Two side slant pockets with signature staple details',
  //       'Back welt pockets',
  //       'Tonal scar seams throughout',
  //       'Tonal scar seams throughout',
  //     ],
  //     price: 67000,
  //     discountPer: 70,
  //     sizes: [
  //       { size: 's', isAvailable: false },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: false },
  //       { size: 'xl', isAvailable: true },
  //       { size: 'xxl', isAvailable: false },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: true,
  //     stock: 6,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'arpenteur leather jacket',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     collection: '2020 Fall/Winter collection',
  //     images: [
  //       'arpenteur_leather_jacket_black_1',
  //       'arpenteur_leather_jacket_black_2',
  //       'arpenteur_leather_jacket_black_3',
  //       'arpenteur_leather_jacket_black_4',
  //     ],
  //     color: 'black',
  //     sku: 'arpenteur-h21~black',
  //     desc: 'Suede Jacket by ISAAC SELLAM in Black',
  //     details: [
  //       'Band collar',
  //       'Fitted',
  //       'Two-way zip closure',
  //       'Side zip pockets',
  //       'Scar seams throughout',
  //       'Back signature staple details',
  //       'Raw-edge hem',
  //       'Model wearing size s',
  //     ],
  //     price: 149000,
  //     discountPer: 25,
  //     sizes: [
  //       { size: 's', isAvailable: true },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: true },
  //       { size: 'xl', isAvailable: false },
  //       { size: 'xxl', isAvailable: true },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: false,
  //     stock: 5,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'arpenteur leather jacket',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     collection: '2020 Fall/Winter collection',
  //     images: [
  //       'arpenteur_leather_jacket_black_1',
  //       'arpenteur_leather_jacket_black_2',
  //       'arpenteur_leather_jacket_black_3',
  //       'arpenteur_leather_jacket_black_4',
  //     ],
  //     color: 'black',
  //     sku: 'arpenteur-h21~black',
  //     desc: 'Suede Jacket by ISAAC SELLAM in Black',
  //     details: [
  //       'Band collar',
  //       'Fitted',
  //       'Two-way zip closure',
  //       'Side zip pockets',
  //       'Scar seams throughout',
  //       'Back signature staple details',
  //       'Raw-edge hem',
  //       'Model wearing size s',
  //     ],
  //     price: 149000,
  //     discountPer: 25,
  //     sizes: [
  //       { size: 's', isAvailable: true },
  //       { size: 'm', isAvailable: true },
  //       { size: 'l', isAvailable: true },
  //       { size: 'xl', isAvailable: false },
  //       { size: 'xxl', isAvailable: true },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: false,
  //     stock: 12,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'arrete tshirt',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     collection: '2020 Fall/Winter collection',
  //     images: [
  //       'arrete_tshirt_black_1',
  //       'arrete_tshirt_black_2',
  //       'arrete_tshirt_black_3',
  //       'arrete_tshirt_black_4',
  //     ],
  //     color: 'black',
  //     sku: 'arrete-h21~black',
  //     desc: 'Long Cotton T-Shirt by ISAAC SELLAM in Black',
  //     details: [
  //       'Round neck',
  //       'Standard fit',
  //       'Taped tonal seams',
  //       'Glove cuffs',
  //       'Raw-edge and hem',
  //       'Model wearing size M',
  //     ],
  //     price: 39500,
  //     discountPer: 30,
  //     sizes: [
  //       { size: 's', isAvailable: false },
  //       { size: 'm', isAvailable: false },
  //       { size: 'l', isAvailable: true },
  //       { size: 'xl', isAvailable: true },
  //       { size: 'xxl', isAvailable: true },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: false,
  //     stock: 23,
  //   });
  //   dataBase.collection('men').add({
  //     id: uuidv4(),
  //     name: 'arrete tshirt',
  //     designer: 'isaac sellam',
  //     category: 'clothing',
  //     collection: '2020 Fall/Winter collection',
  //     images: [
  //       'arrete_tshirt_dark_grey_1',
  //       'arrete_tshirt_dark_grey_2',
  //       'arrete_tshirt_dark_grey_3',
  //       'arrete_tshirt_dark_grey_4',
  //     ],
  //     color: 'dark grey',
  //     sku: 'arrete-h21~dark grey',
  //     desc: 'Long Cotton T-Shirt by ISAAC SELLAM in Darck Grey',
  //     details: [
  //       'Round neck',
  //       'Standard fit',
  //       'Taped tonal seams',
  //       'Glove cuffs',
  //       'Raw-edge and hem',
  //       'Model wearing size M',
  //     ],
  //     price: 39500,
  //     discountPer: 30,
  //     sizes: [
  //       { size: 's', isAvailable: false },
  //       { size: 'm', isAvailable: false },
  //       { size: 'l', isAvailable: true },
  //       { size: 'xl', isAvailable: true },
  //       { size: 'xxl', isAvailable: true },
  //       { size: 'xxxl', isAvailable: false },
  //     ],
  //     popularity: false,
  //     stock: 20,
  //   });

  //   --------------------

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'arrete tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     ' arrete_tshirt_red_1',
  //     'arrete_tshirt_red_2',
  //     'arrete_tshirt_red_3',
  //     'arrete_tshirt_red_4',
  //   ],
  //   color: 'red',
  //   sku: 'arrete-h21~red',
  //   desc: 'Long Cotton T-Shirt by ISAAC SELLAM in Red',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Taped tonal seams',
  //     'Glove cuffs',
  //     'Raw-edge and hem',
  //     'Model wearing size M',
  //   ],
  //   price: 39500,
  //   discountPer: 30,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 13,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'arrete tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'arrete_tshirt_white_1',
  //     'arrete_tshirt_white_2',
  //     'arrete_tshirt_white_3',
  //     'arrete_tshirt_white_4',
  //   ],
  //   color: 'white',
  //   sku: 'arrete-h21~white',
  //   desc: 'Long Cotton T-Shirt by ISAAC SELLAM in White',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Taped tonal seams',
  //     'Glove cuffs',
  //     'Raw-edge and hem',
  //     'Model wearing size M',
  //   ],
  //   price: 39500,
  //   discountPer: 30,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 4,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'debloque',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   images: [
  //     'debloque_white_1',
  //     'debloque_white_2',
  //     'debloque_white_3',
  //     'debloque_white_4',
  //   ],
  //   color: 'white',
  //   sku: 'debloque-h21~white',
  //   desc: 'The model is wearing size S',
  //   price: 29000,
  //   discountPer: 20,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: false },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 5,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'debloque tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'debloque_tshirt_black_1',
  //     'debloque_tshirt_black_2',
  //     'debloque_tshirt_black_3',
  //     'debloque_tshirt_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'debloque-h21~black',
  //   desc: 'Cotton T-Shirt by ISAAC SELLAM in Black',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Washed',
  //     'Taped tonal seams',
  //     'Raw-edge long hem',
  //     'Model wearing size M',
  //   ],
  //   price: 29000,
  //   discountPer: 29,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 8,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'debloque tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'debloque_tshirt_dark_grey_1',
  //     'debloque_tshirt_dark_grey_2',
  //     'debloque_tshirt_dark_grey_3',
  //     'debloque_tshirt_dark_grey_4',
  //   ],
  //   color: 'dark grey',
  //   sku: 'debloque-h21~dark grey',
  //   desc: 'Cotton T-Shirt by ISAAC SELLAM in Dark grey',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Washed',
  //     'Taped tonal seams',
  //     'Raw-edge long hem',
  //     'Model wearing size M',
  //   ],
  //   price: 29000,
  //   discountPer: 29,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 8,
  // });

  // // Crime
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'debloque tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'debloque_tshirt_red_1',
  //     'debloque_tshirt_red_2',
  //     'debloque_tshirt_red_3',
  //     'debloque_tshirt_red_4',
  //   ],
  //   color: 'red',
  //   sku: 'debloque-h21~red',
  //   desc: 'Cotton T-Shirt by ISAAC SELLAM in Red',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Washed',
  //     'Taped tonal seams',
  //     'Raw-edge long hem',
  //     'Model wearing size M',
  //   ],
  //   price: 29000,
  //   discountPer: 29,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 15,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'ecorne tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'ecorne_tshirt_black_1',
  //     'ecorne_tshirt_black_2',
  //     'ecorne_tshirt_black_3',
  //     'ecorne_tshirt_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'ecorne-h21~black',
  //   desc: 'Cotton T-Shirt by ISAAC SELLAM in Black',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Washed',
  //     'Taped tonal seams',
  //     'Raw-edge long hem',
  //     'Model wearing size M',
  //   ],
  //   price: 37000,
  //   discountPer: 30,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 13,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'ecorne tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'ecorne_tshirt_dark_grey_1',
  //     'ecorne_tshirt_dark_grey_2',
  //     'ecorne_tshirt_dark_grey_3',
  //     'ecorne_tshirt_dark_grey_4',
  //   ],
  //   color: 'dark grey',
  //   sku: 'ecorne-h21~dark grey',
  //   desc: 'Cotton T-Shirt by ISAAC SELLAM in Dark Grey',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Washed',
  //     'Taped tonal seams',
  //     'Raw-edge long hem',
  //     'Model wearing size M',
  //   ],
  //   price: 37000,
  //   discountPer: 30,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 14,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'ecorne tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'ecorne_tshirt_red_1',
  //     'ecorne_tshirt_red_2',
  //     'ecorne_tshirt_red_3',
  //     'ecorne_tshirt_red_4',
  //   ],
  //   color: 'red',
  //   sku: 'ecorne-h21~red',
  //   desc: 'Cotton T-Shirt by ISAAC SELLAM in Red',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Washed',
  //     'Taped tonal seams',
  //     'Raw-edge long hem',
  //     'Model wearing size M',
  //   ],
  //   price: 37000,
  //   discountPer: 30,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 10,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'ecorne tshirt',
  //   designer: 'isaac sellam',
  //   category: 'clothing',
  //   collection: '2020 Fall/Winter collection',
  //   images: [
  //     'ecorne_tshirt_white_1',
  //     'ecorne_tshirt_white_2',
  //     'ecorne_tshirt_white_3',
  //     'ecorne_tshirt_white_4',
  //   ],
  //   color: 'white',
  //   sku: 'ecorne-h21~white',
  //   desc: 'Cotton T-Shirt by ISAAC SELLAM in White',
  //   details: [
  //     'Round neck',
  //     'Standard fit',
  //     'Washed',
  //     'Taped tonal seams',
  //     'Raw-edge long hem',
  //     'Model wearing size M',
  //   ],
  //   price: 37000,
  //   discountPer: 30,
  //   sizes: [
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 3,
  // });

  // // Feel-good
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'carson',
  //   designer: 'the last conspiracy',
  //   category: 'footwear',
  //   images: [
  //     'carson_black_1',
  //     'carson_black_2',
  //     ' carson_black_3',
  //     'carson_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'tlc2484~black',
  //   desc: 'Mid Cut Suede Sneakers by THE LAST CONSPIRACY in Black ',
  //   details: [
  //     'Round toe',
  //     'Round laces',
  //     'Horse suede upper',
  //     'Cow leather lining',
  //     'Pillow sole',
  //     'Heel height: approx. 3.5cm',
  //   ],
  //   price: 25500,
  //   discountPer: 50,
  //   sizes: [
  //     { size: '41seu', isAvailable: false },
  //     { size: '42seu', isAvailable: false },
  //     { size: '43seu', isAvailable: false },
  //     { size: '44seu', isAvailable: false },
  //     { size: '45seu', isAvailable: true },
  //     { size: '46seu', isAvailable: true },
  //   ],
  //   popularity: true,
  //   stock: 5,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'riley',
  //   designer: 'the last conspiracy',
  //   category: 'footwear',
  //   images: [
  //     'riley_black_1',
  //     'riley_black_2',
  //     'riley_black_3',
  //     'riley_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'tlc2484~black',
  //   desc: 'Slip-On Horse Sneakers by THE LAST CONSPIRACY in Black',
  //   details: [
  //     'Round toe',
  //     'Low cut',
  //     'Elastic front',
  //     'Horse suede upper',
  //     'Cow leather lining ',
  //     'Pillow sole',
  //     'Heel height: approx. 3.5cm',
  //   ],
  //   price: 24000,
  //   discountPer: 50,
  //   sizes: [
  //     { size: '41seu', isAvailable: false },
  //     { size: '42seu', isAvailable: false },
  //     { size: '43seu', isAvailable: false },
  //     { size: '44seu', isAvailable: false },
  //     { size: '45seu', isAvailable: true },
  //     { size: '46seu', isAvailable: true },
  //   ],
  //   popularity: true,
  //   stock: 8,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'caden',
  //   designer: 'the last conspiracy',
  //   category: 'footwear',
  //   images: [
  //     'caden_black_1',
  //     'caden_black_2',
  //     'caden_black_3',
  //     'caden_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'tlc2484~black',
  //   desc: 'Low- Cut Horse Sneakers by THE LAST CONSPIRACY in Black',
  //   details: [
  //     'Round toe',
  //     'Leather laces',
  //     'Horse suede upper',
  //     'Cow leather lining',
  //     'Pillow sole',
  //     'Heel height: approx. 3.5cm',
  //   ],
  //   price: 22000,
  //   discountPer: 50,
  //   sizes: [
  //     { size: '41seu', isAvailable: false },
  //     { size: '42seu', isAvailable: false },
  //     { size: '43seu', isAvailable: false },
  //     { size: '44seu', isAvailable: false },
  //     { size: '45seu', isAvailable: true },
  //     { size: '46seu', isAvailable: true },
  //   ],
  //   popularity: true,
  //   stock: 9,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: '10sei0otto coats',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['sei0otto_coats_black_1', 'sei0otto_coats_black_2'],
  //   color: 'black',
  //   sku: '1300COAT~BLACK',
  //   desc: 'Wool Overcoat by 10SEI0OTTO in Black',
  //   details: [
  //     'Shawl lapels',
  //     'Standard fit',
  //     'Button closure',
  //     'Front patch pockets',
  //     'Cotton cuff detail',
  //     'Finished hem',
  //     'Model is wearing size M',
  //   ],
  //   price: 95600,
  //   discountPer: 25,
  //   sizes: [
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 20,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: '10sei0otto jackets',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['sei0otto_jackets_black_1', 'sei0otto_jackets_black_2'],
  //   color: 'black',
  //   sku: 'ABEL-BRISTOL~BLACK',
  //   desc: 'Asymmetric Wool Jacket by 10SEI0OTTO in Black',
  //   details: [
  //     'High collar',
  //     'Standard fit',
  //     'Asymmetric two- zip closure',
  //     'Side slit pockets',
  //     'Finished hem',
  //     'Model is wearing size L',
  //   ],
  //   price: 73500,
  //   discountPer: 20,
  //   sizes: [
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: false },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 10,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: '10sei0otto pants',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['sei0otto_pants_grey_1', 'sei0otto_pants_grey_2'],
  //   color: 'grey',
  //   sku: 'EDO~GREY',
  //   desc: 'Dyed Cotton Pants by 10SEI0OTTO in Grey',
  //   details: [
  //     'Natural waist rise',
  //     'Relaxed fit',
  //     'Concealed buttons closure',
  //     'Side round pockets',
  //     'Hand-dyed details at knees',
  //     'Dye-effect may vary',
  //     'Asymmetric cuffs',
  //     'Model wearing size XS',
  //   ],
  //   price: 35900,
  //   discountPer: 10,
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 10,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: '10sei0otto t-shirt',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['sei0otto_tshirt_black_1', 'sei0otto_tshirt_black_2'],
  //   color: 'black',
  //   sku: 'T-SHIRT-LS~BLACK',
  //   desc: 'Cotton T-Shirt by 10SEI0OTTO in Black',
  //   details: [
  //     'Crewneck',
  //     'Slim fit',
  //     'Tonal seam details',
  //     'Raw-edge trim cuffs and hem',
  //     'Model is wearing size',
  //   ],
  //   price: 18500,
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 14,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: '10sei0otto t-shirt',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['sei0otto_tshirt_brown_1', 'sei0otto_tshirt_brown_2'],
  //   color: 'brown',
  //   sku: 'T-SHIRT-LS~BROWN',
  //   desc: 'Cotton T-Shirt by 10SEI0OTTO in Black',
  //   details: [
  //     'Crewneck',
  //     'Slim fit',
  //     'Tonal seam details',
  //     'Raw-edge trim cuffs and hem',
  //     'Model is wearing size',
  //   ],
  //   price: 18500,
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 14,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: '10sei0otto t-shirt',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['sei0otto_tshirt_grey_1', 'sei0otto_tshirt_grey_2'],
  //   color: 'grey',
  //   sku: 'T-SHIRT-LS~GREY',
  //   desc: 'Cotton T-Shirt by 10SEI0OTTO in Grey',
  //   details: [
  //     'Crewneck',
  //     'Slim fit',
  //     'Tonal seam details',
  //     'Raw-edge trim cuffs and hem',
  //     'Model is wearing size',
  //   ],
  //   price: 18500,
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 14,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: '10sei0otto t-shirt',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['sei0otto_tshirt_stone_1', 'sei0otto_tshirt_stone_2'],
  //   color: 'stone',
  //   sku: 'T-SHIRT-LS~STONE',
  //   desc: 'Cotton T-Shirt by 10SEI0OTTO in Stone',
  //   details: [
  //     'Crewneck',
  //     'Slim fit',
  //     'Tonal seam details',
  //     'Raw-edge trim cuffs and hem',
  //     'Model is wearing size',
  //   ],
  //   price: 18500,
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 14,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'pants',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   images: ['pants_black_1', 'pants_black_2'],
  //   color: 'black',
  //   sku: '3219TD~BLACK',
  //   desc: 'Pants by 10SEI0OTTO in Black',
  //   details: [
  //     'Low rise',
  //     'Slim fit',
  //     'Button and zipper closure',
  //     'Two side seam pockets',
  //     'Two back seam pockets',
  //     'Contrasting seam details',
  //   ],
  //   price: 43500,
  //   discountPer: 50,
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: false },
  //   ],
  //   popularity: false,
  //   stock: 9,
  // });
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'vest',
  //   designer: '10sei0otto',
  //   category: 'clothing',
  //   collection: 'SS20 New Collection',
  //   images: ['vest_mustard_1', 'vest_mustard_2'],
  //   color: 'mustard',
  //   sku: '3212S~MUSTARD',
  //   desc: 'Leather Vest by 10SEI0OTTO in Mustard',
  //   details: [
  //     'Low standing collar',
  //     'Standard fit',
  //     'Two- zip closure',
  //     'Chest slit pockets',
  //     'Side flap pockets',
  //     'Scar stitching details',
  //     'Straight and finished hem',
  //   ],
  //   price: 132500,
  //   discountPer: 55,
  //   sizes: [{ size: 'm', isAvailable: true }],
  //   popularity: false,
  //   stock: 5,
  // });

  // ------------------------------
  // Footwear category
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'y-3 orisan',
  //   designer: 'y-3',
  //   category: 'footwear',
  //   images: [
  //     'y-3_orisan_blk_whi_1',
  //     'y-3_orisan_blk_whi_2',
  //     'y-3_orisan_blk_whi_3',
  //     'y-3_orisan_blk_whi_4',
  //   ],
  //   color: 'black white',
  //   sku: 'FZ4319~BLK WHI',
  //   details: [
  //     'Lace closure',
  //     'Mesh and leather upper',
  //     'GORE-TEX lining for waterproof, breathable performance',
  //     'Distinctive Boost midsole',
  //     'Rubber outsole',
  //     'Product color: Core White / Core White / Black',
  //   ],
  //   price: 30000,
  //   discountPer: 100,
  //   sizes: [
  //     { size: '7', isAvailable: true },
  //     { size: '7.5', isAvailable: true },
  //     { size: '8', isAvailable: false },
  //     { size: '8.5', isAvailable: true },
  //     { size: '9', isAvailable: true },
  //     { size: '9.5', isAvailable: true },
  //     { size: '10', isAvailable: true },
  //     { size: '10.5', isAvailable: true },
  //     { size: '11', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 15,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'y-3 orisan',
  //   designer: 'y-3',
  //   category: 'footwear',
  //   images: [
  //     'y-3_orisan_blk_grey_1',
  //     'y-3_orisan_blk_grey_2',
  //     'y-3_orisan_blk_grey_3',
  //     'y-3_orisan_blk_grey_4',
  //   ],
  //   color: 'black grey',
  //   sku: 'FZ4317~BLACK GREY',
  //   details: [
  //     'Lace closure',
  //     'Mesh upper',
  //     'Leather lining',
  //     'Distinctive Boost midsole',
  //     'Rubber outsole',
  //     'Product color: Black / Grey One / Core White',
  //   ],
  //   price: 30000,
  //   discountPer: 100,
  //   sizes: [
  //     { size: '7', isAvailable: true },
  //     { size: '7.5', isAvailable: true },
  //     { size: '8', isAvailable: true },
  //     { size: '8.5', isAvailable: true },
  //     { size: '9', isAvailable: true },
  //     { size: '9.5', isAvailable: true },
  //     { size: '10', isAvailable: true },
  //     { size: '10.5', isAvailable: true },
  //     { size: '11', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 10,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'y-3 orisan',
  //   designer: 'y-3',
  //   category: 'footwear',
  //   images: [
  //     'y-3_orisan_white_1',
  //     'y-3_orisan_white_2',
  //     'y-3_orisan_white_3',
  //     'y-3_orisan_white_4',
  //   ],
  //   color: 'white',
  //   sku: '	FX1412~WHITE',
  //   desc: 'Orisan Cushioned Sneakers by Y-3 in White',
  //   details: [
  //     'Lace-up',
  //     'Suede, leather and double-layer mesh upper',
  //     'Y-3 logo on tongue and heel',
  //     'Back pull tab',
  //     'Rubber sole',
  //   ],
  //   price: 28000,
  //   discountPer: 30,
  //   sizes: [
  //     { size: '4.5', isAvailable: false },
  //     { size: '5', isAvailable: true },
  //     { size: '5.5', isAvailable: true },
  //     { size: '6', isAvailable: false },
  //     { size: '6.5', isAvailable: false },
  //     { size: '7', isAvailable: false },
  //     { size: '8', isAvailable: true },
  //     { size: '8.5', isAvailable: false },
  //     { size: '9', isAvailable: true },
  //     { size: '9.5', isAvailable: false },
  //     { size: '10.5', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 10,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'y-3 orisan',
  //   designer: 'y-3',
  //   category: 'footwear',
  //   images: [
  //     'y-3_orisan_blk_whi_1',
  //     'y-3_orisan_blk_whi_2',
  //     'y-3_orisan_blk_whi_3',
  //     'y-3_orisan_blk_whi_4',
  //   ],
  //   color: 'blk whi',
  //   sku: 'FX1413~BLK WHI',
  //   desc: 'Orisan Cushioned Sneakers by Y-3 in Black & White',
  //   details: [
  //     'Lace-up',
  //     'Suede, leather and double-layer mesh upper',
  //     'Y-3 logo on tongue and heel',
  //     'Back pull tab',
  //     'Rubber sole',
  //   ],
  //   price: 28000,
  //   discountPer: 30,
  //   sizes: [
  //     { size: '4.5', isAvailable: false },
  //     { size: '5', isAvailable: true },
  //     { size: '5.5', isAvailable: true },
  //     { size: '6', isAvailable: false },
  //     { size: '6.5', isAvailable: false },
  //     { size: '7', isAvailable: false },
  //     { size: '8', isAvailable: true },
  //     { size: '8.5', isAvailable: false },
  //     { size: '9', isAvailable: true },
  //     { size: '9.5', isAvailable: true },
  //     { size: '10.5', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 5,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'y-3 shiku run',
  //   designer: 'y-3',
  //   category: 'footwear',
  //   images: [
  //     'y-3_shiku_run_white_grey_1',
  //     'y-3_shiku_run_white_grey_2',
  //     'y-3_shiku_run_white_grey_3',
  //     'y-3_shiku_run_white_grey_4',
  //   ],
  //   color: 'white grey',
  //   sku: 'FZ4323~WHITE GREY',
  //   details: [
  //     'Lace closure',
  //     'Nylon and mesh upper',
  //     ' Leather lining',
  //     'Cord system embroidered around upper',
  //     'EVA midsole and rubber outsole',
  //     'Product colour: Core White / Grey One / Black',
  //   ],
  //   price: 28000,
  //   sizes: [
  //     { size: '7', isAvailable: true },
  //     { size: '7.5', isAvailable: true },
  //     { size: '8', isAvailable: true },
  //     { size: '8.5', isAvailable: true },
  //     { size: '9', isAvailable: false },
  //     { size: '9.5', isAvailable: true },
  //     { size: '10', isAvailable: true },
  //     { size: '10.5', isAvailable: true },
  //     { size: '11', isAvailable: true },
  //     { size: '11.5', isAvailable: true },
  //     { size: '12', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 8,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'y-3 boxing shoes',
  //   designer: 'y-3',
  //   category: 'footwear',
  //   images: [
  //     'y-3_boxing_shoes_black_1',
  //     'y-3_boxing_shoes_black_2',
  //     'y-3_boxing_shoes_black_3',
  //     'y-3_boxing_shoes_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'FZ4476~BLACK',
  //   details: [
  //     'Lace closure',
  //     'Leather upper with suede detailing',
  //     'Leather and canvas lining',
  //     'Poron performance cushioning sockliner',
  //     'EVA midsole and rubber outsole',
  //   ],
  //   price: 21500,
  //   sizes: [
  //     { size: '7.5', isAvailable: true },
  //     { size: '8', isAvailable: true },
  //     { size: '8.5', isAvailable: true },
  //     { size: '9', isAvailable: true },
  //     { size: '9.5', isAvailable: true },
  //     { size: '10', isAvailable: true },
  //     { size: '10.5', isAvailable: true },
  //     { size: '11', isAvailable: true },
  //     { size: '11.5', isAvailable: true },
  //     { size: '12', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 14,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'rbrsl scarpa',
  //   designer: 'oxs rubber soul',
  //   category: 'footwear',
  //   images: [
  //     'y-3_rbrsl_scarpa_black_1',
  //     'y-3_rbrsl_scarpa_black_2',
  //     'y-3_rbrsl_scarpa_black_3',
  //     'y-3_rbrsl_scarpa_black_4',
  //   ],
  //   color: 'black',
  //   sku: '2296U~BLACK',
  //   price: 29000,
  //   sizes: [
  //     { size: '40seu', isAvailable: true },
  //     { size: '41seu', isAvailable: true },
  //     { size: '42seu', isAvailable: false },
  //     { size: '43seu', isAvailable: false },
  //     { size: '44seu', isAvailable: true },
  //     { size: '45seu', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 10,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'rbrsl scarpa',
  //   designer: 'oxs rubber soul',
  //   category: 'footwear',
  //   images: [
  //     'y-3_rbrsl_scarpa_green_1',
  //     'y-3_rbrsl_scarpa_green_2',
  //     'y-3_rbrsl_scarpa_green_3',
  //     'y-3_rbrsl_scarpa_green_4',
  //   ],
  //   color: 'green',
  //   sku: '2296U~GREEN',
  //   price: 29000,
  //   sizes: [
  //     { size: '40seu', isAvailable: true },
  //     { size: '41seu', isAvailable: true },
  //     { size: '42seu', isAvailable: true },
  //     { size: '43seu', isAvailable: true },
  //     { size: '44seu', isAvailable: true },
  //     { size: '45seu', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 4,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'rbrsl scarpa',
  //   designer: 'oxs rubber soul',
  //   category: 'footwear',
  //   images: [
  //     'y-3_rbrsl_scarpa_black_white_1',
  //     'y-3_rbrsl_scarpa_black_white_2',
  //     'y-3_rbrsl_scarpa_black_white_3',
  //     'y-3_rbrsl_scarpa_black_white_4',
  //   ],
  //   color: 'black white',
  //   sku: '2296U~BLK WHI',
  //   price: 29000,
  //   sizes: [
  //     { size: '40seu', isAvailable: true },
  //     { size: '41seu', isAvailable: true },
  //     { size: '42seu', isAvailable: true },
  //     { size: '43seu', isAvailable: true },
  //     { size: '44seu', isAvailable: true },
  //     { size: '45seu', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 8,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'rbrsl scarpa',
  //   designer: 'oxs rubber soul',
  //   category: 'footwear',
  //   images: [
  //     'y-3_rbrsl_scarpa_blk_whi_1',
  //     'y-3_rbrsl_scarpa_blk_whi_2',
  //     'y-3_rbrsl_scarpa_blk_whi_3',
  //     'y-3_rbrsl_scarpa_blk_whi_4',
  //   ],
  //   color: 'blk whi',
  //   sku: '2294U~BLK WHI',
  //   price: 31500,
  //   sizes: [
  //     { size: '40seu', isAvailable: true },
  //     { size: '41seu', isAvailable: true },
  //     { size: '42seu', isAvailable: true },
  //     { size: '43seu', isAvailable: true },
  //     { size: '44seu', isAvailable: true },
  //     { size: '45seu', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 12,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   name: 'rbrsl scarpa',
  //   designer: 'oxs rubber soul',
  //   category: 'footwear',
  //   images: [
  //     'y-3_rbrsl_scarpa_blk_1',
  //     'y-3_rbrsl_scarpa_blk_2',
  //     'y-3_rbrsl_scarpa_blk_3',
  //     'y-3_rbrsl_scarpa_blk_4',
  //   ],
  //   color: 'blk',
  //   sku: '2294U~BLACK',
  //   price: 31500,
  //   sizes: [
  //     { size: '40seu', isAvailable: true },
  //     { size: '41seu', isAvailable: true },
  //     { size: '42seu', isAvailable: true },
  //     { size: '43seu', isAvailable: true },
  //     { size: '44seu', isAvailable: true },
  //     { size: '45seu', isAvailable: true },
  //   ],
  //   popularity: false,
  //   stock: 12,
  // });

  /* Women
      ============================================ */
  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   name: '139dce jacket',
  //   designer: '139dce',
  //   images: [
  //     'dce_jacket_black_1',
  //     'dce_jacket_black_2',
  //     'dce_jacket_black_3',
  //     'dce_jacket_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'sut706~black',
  //   desc: 'Elongated Blazer Jacket by 139DEC in Black',
  //   details: [
  //     'Shawl lapels',
  //     'Standard fit',
  //     'Buttons closure',
  //     'Broad welt side pockets',
  //     'Elongated back',
  //     'Adjustable bustle drawstring',
  //     'Finished hem',
  //     'Model is wearing size S',
  //   ],
  //   price: 33000,
  //   discountPer: 33,
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: false },
  //   ],
  //   popularity: true,
  //   stock: 10,
  // });
  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   name: 'coat',
  //   designer: 'avant toi',
  //   images: ['coat_black_1', 'coat_black_2', 'coat_black_3', 'coat_black_4'],
  //   collection: 'SS20 New Collection',
  //   color: 'black',
  //   sku: 'd6784gabdl~black',
  //   desc: 'Sparkle-Embellished Knit Coat by AVANT TOI in Black',
  //   details: [
  //     'Standard fit',
  //     'Buttons closure',
  //     'Front patch pockets',
  //     'Back center vent',
  //     'Gold and silver-toned metallic details',
  //     'Frayed edges',
  //   ],
  //   price: 131500,
  //   discountPer: 50,
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //   ],
  //   popularity: true,
  //   stock: 12,
  // });
  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   name: 'rta stella',
  //   designer: 'rta',
  //   images: [
  //     'rta_stella_black_1',
  //     'rta_stella_black_2',
  //     'rta_stella_black_3',
  //     'rta_stella_black_4',
  //   ],
  //   color: 'black',
  //   sku: 'wf9353-4014~black',
  //   desc: 'Layered Pinstripe Blazer by RTA in Black',
  //   details: [
  //     'Double notched lapels ',
  //     'Standard fit',
  //     'Open front',
  //     'Metallic silver stripes',
  //     'Notched hem',
  //     'Model wearing size: S',
  //   ],
  //   price: 68500,
  //   discountPer: 50,
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: true },
  //   ],
  //   popularity: true,
  //   stock: 20,
  // });
  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   name: 'trasint leather jacket',
  //   designer: 'trasint',
  //   images: [
  //     'trasint_leather_jacket_brown_1',
  //     'trasint_leather_jacket_brown_2',
  //     'trasint_leather_jacket_brown_3',
  //     'trasint_leather_jacket_brown_4',
  //   ],
  //   color: 'brown',
  //   sku: 'dtrk4391~brown',
  //   desc: 'Leather- Linen Blend Blazer by TRANSIT in Brown',
  //   details: [
  //     'Notched lapels',
  //     'Standard fit',
  //     'Buttons closure',
  //     'Front flap pockets',
  //     'Tonal seams',
  //     'Straight finished hem',
  //     'Model wearing size: 1',
  //   ],
  //   price: 85500,
  //   discountPer: 50,
  //   sizes: [
  //     { size: '1', isAvailable: true },
  //     { size: '2', isAvailable: false },
  //     { size: '3', isAvailable: false },
  //     { size: '4', isAvailable: true },
  //   ],
  //   popularity: true,
  //   stock: 10,
  // });
  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   name: 'y-3 adilette slide sandals',
  //   designer: 'y-3',
  //   images: [
  //     'y3_adilette_white_1',
  //     'y3_adilette_white_2',
  //     'y3_adilette_white_3',
  //     ' y3_adilette_white_4',
  //   ],
  //   collection: 'SS20 New Collection',
  //   color: 'white',
  //   sku: 'fw9742~WHITE',
  //   desc: 'Multicolored Graphic Slide Sandals by Y-3  in White',
  //   details: [
  //     'Round and open toe',
  //     'Slip-on style',
  //     'Graphic printed upper',
  //     'Rubber sole',
  //     'Approx. 2.5cm height',
  //   ],
  //   price: 10500,
  //   discountPer: 1,
  //   sizes: [
  //     { size: '5', isAvailable: false },
  //     { size: '6', isAvailable: true },
  //     { size: '7', isAvailable: true },
  //     { size: '8', isAvailable: true },
  //   ],
  //   popularity: true,
  //   stock: 12,
  // });
}
